name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: vapor/swiftly-action@v0.2
      with:
        toolchain: latest

    - name: Build
      run: swift build --verbose

    - name: Run tests
      run: swift test --verbose
